In [4]:
import pandas as pd
from sqlalchemy import create_engine, text

# Database credentials
username = 'admin'
password = 'admin%40123'
ip_address = '100.90.162.48'
port = '5432'
DB_URI = f'postgresql://{username}:{password}@{ip_address}:{port}'

db_name = "chicago_crime"

new_engine = create_engine(f'{DB_URI}/{db_name}')

In [5]:
from sqlalchemy.orm import sessionmaker

Session = sessionmaker(bind=new_engine)
session = Session()

In [10]:
with new_engine.connect() as conn:
    result = conn.execute(text("SELECT count(*) FROM chicago_crime where primary_type = 'THEFT'"))

print(result.fetchall())

[(197,)]

In [11]:
import pandas as pd

df = pd.read_csv('Crimes_2020_to_Present_20260304.csv')

In [12]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14121954,JK163066,02/23/2026 12:00:00 AM,069XX S CRANDON AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,True,...,5.0,43.0,26,1192522.0,1859423.0,2026,03/02/2026 03:42:09 PM,41.769231,-87.569855,"(41.769231153, -87.569854828)"
1,14119135,JK159501,02/23/2026 12:00:00 AM,018XX N FAIRFIELD AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,1.0,22.0,06,1157750.0,1912034.0,2026,03/02/2026 03:42:09 PM,41.914378,-87.695882,"(41.914378059, -87.695881521)"
2,14119149,JK159544,02/23/2026 12:00:00 AM,016XX W MORSE AVE,1754,OFFENSE INVOLVING CHILDREN,AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY M...,OTHER (SPECIFY),False,True,...,49.0,1.0,02,1164302.0,1946138.0,2026,03/02/2026 03:42:09 PM,42.007825,-87.670842,"(42.007824765, -87.670841822)"
3,14124471,JK163214,02/23/2026 12:00:00 AM,018XX S AVERS AVE,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,APARTMENT,False,True,...,24.0,29.0,08B,NaN,NaN,2026,03/02/2026 03:42:09 PM,NaN,NaN,NaN
4,14119441,JK159902,02/23/2026 12:00:00 AM,063XX W CUYLER AVE,0810,THEFT,OVER $500,STREET,False,False,...,38.0,15.0,06,1133380.0,1926251.0,2026,03/02/2026 03:42:09 PM,41.953853,-87.785080,"(41.953853257, -87.785080407)"

In [13]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

/var/folders/z7/9ddbbmc16r938ffjjlj2ssv40000gn/T/ipykernel_9140/2263964175.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [15]:
df

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,14121954,JK163066,2026-02-23 00:00:00,069XX S CRANDON AVE,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,True,...,5.0,43.0,26,1192522.0,1859423.0,2026,03/02/2026 03:42:09 PM,41.769231,-87.569855,"(41.769231153, -87.569854828)"
1,14119135,JK159501,2026-02-23 00:00:00,018XX N FAIRFIELD AVE,0710,THEFT,THEFT FROM MOTOR VEHICLE,STREET,False,False,...,1.0,22.0,06,1157750.0,1912034.0,2026,03/02/2026 03:42:09 PM,41.914378,-87.695882,"(41.914378059, -87.695881521)"
2,14119149,JK159544,2026-02-23 00:00:00,016XX W MORSE AVE,1754,OFFENSE INVOLVING CHILDREN,AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY M...,OTHER (SPECIFY),False,True,...,49.0,1.0,02,1164302.0,1946138.0,2026,03/02/2026 03:42:09 PM,42.007825,-87.670842,"(42.007824765, -87.670841822)"
3,14124471,JK163214,2026-02-23 00:00:00,018XX S AVERS AVE,1750,OFFENSE INVOLVING CHILDREN,CHILD ABUSE,APARTMENT,False,True,...,24.0,29.0,08B,NaN,NaN,2026,03/02/2026 03:42:09 PM,NaN,NaN,NaN
4,14119441,JK159902,2026-02-23 00:00:00,063XX W CUYLER AVE,0810,THEFT,OVER $500,STREET,False,False,...,38.0,15.0,06,1133380.0,1926251.0,2026,03/02/2026 03:42:09 PM,41.953853,-87.785080,"(41.953853257, -87.785080407)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410081,11998679,JD173245,2020-03-04 00:40:00,095XX S YATES AVE,0560,ASSAULT,SIMPLE,STREET,False,False,...,10.0,51.0,08A,1194082.0,1842136.0,2020,03/11/2020 03:40:48 PM,41.721756,-87.564703,"(41.721756053, -87.564702726)"
1410082,11999936,JD174770,2020-03-04 00:30:00,027XX W POTOMAC AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,26.0,24.0,06,1157974.0,1908533.0,2020,03/11/2020 03:40:48 PM,41.904766,-87.695154,"(41.904766459, -87.695154275)"
1410083,11998813,JD173366,2020-03-04 00:30:00,011XX W DIVERSEY PKWY,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,44.0,6.0,07,1168240.0,1918749.0,2020,03/11/2020 03:40:48 PM,41.932584,-87.657148,"(41.932583967, -87.65714847)"
1410084,11998655,JD173217,2020-03-04 00:27:00,009XX N WALLER AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,True,True,...,29.0,25.0,08B,1138184.0,1905748.0,2020,03/11/2020 03:40:48 PM,41.897505,-87.767917,"(41.897505079, -87.767917077)"
1410085,12000954,JD175908,2020-03-04 00:15:00,024XX N TRIPP AVE,0820,THEFT,$500 AND UNDER,STREET,False,False,...,31.0,20.0,06,1147642.0,1915913.0,2020,03/11/2020 03:40:48 PM,41.925223,-87.732917,"(41.925222557, -87.732917254)"